#!/usr/bin/env bash
# Install nginx on your server, Nginx should be listening on port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo service start nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
