#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it
mysqldump -u root -p "$1" --all-databases > backup.sql
gzip -c backup.sql | cat > "$(date +%d-%m-%Y).tar.gz"
