#!/usr/bin/env bash
# service (init) must say that nginx is not running
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
rm /run/nginx.pid
