#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when
# receiving a SIGQUIT or SIGTERM signal
trap 'echo I hate the kill command; kill -9 $$; sudo rm /var/run/holbertonscript.pid' SIGTERM SIGQUIT
trap "echo Y U no love me?!; kill -9 $$" SIGINT
echo $$ | cat > /var/run/holbertonscript.pid
CONDITION=:
while [ $CONDITION ]
do
    echo "To infinity and beyond"
done
