#!/usr/bin/env bash
#displays Holberton School 10 times, but for the 9th iteration,
#displays Holberton School and then Hi on a new line
COUNTER=1
while [  $COUNTER -le 10 ];
do
    echo "Holberton School"
    if [ $COUNTER -eq 9 ]
    then
	echo "Hi"
    fi
    let COUNTER+=1
done
