#!/usr/bin/env bash
# configures a Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
sed -i '/127.0.0.1 localhost/ c\127.0.0.2 localhost' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
sed -i '/127.0.0.2 localhost/a 8.8.8.8 facebook.com' /etc/hosts
