#!/usr/bin/env bash
# displays all active IPv4 IPs on the machine it's executed on
# ifconfig | grep "inet addr:" | awk -F'[: ]+' '{ print $4 }'
ifconfig | grep "inet addr:" | cut -d':' -f2 | cut -d' ' -f1
