#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
pkill apache2
sudo sed -i "s/listen 80 default_server/listen 8080 default_server/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/80 default_server ipv6only=on/8080 default_server ipv6only=on/g" /etc/nginx/sites-enabled/default
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
